// Stub for wagmi/connectors
export const walletConnect = () => ({
  id: 'walletConnect',
  name: 'WalletConnect',
  ready: true,
  connect: jest.fn(),
  disconnect: jest.fn(),
  getAccounts: jest.fn(),
  getChainId: jest.fn(),
  isConnected: false,
  isConnecting: false,
  isDisconnected: true,
  isUnsupported: false,
  switchChain: jest.fn(),
  watchAccount: jest.fn(),
  watchChainId: jest.fn(),
  watchConnector: jest.fn(),
  watchDisconnect: jest.fn(),
})

export const injected = () => ({
  id: 'injected',
  name: 'Injected',
  ready: true,
  connect: jest.fn(),
  disconnect: jest.fn(),
  getAccounts: jest.fn(),
  getChainId: jest.fn(),
  isConnected: false,
  isConnecting: false,
  isDisconnected: true,
  isUnsupported: false,
  switchChain: jest.fn(),
  watchAccount: jest.fn(),
  watchChainId: jest.fn(),
  watchConnector: jest.fn(),
  watchDisconnect: jest.fn(),
})

export const coinbaseWallet = () => ({
  id: 'coinbaseWallet',
  name: 'Coinbase Wallet',
  ready: true,
  connect: jest.fn(),
  disconnect: jest.fn(),
  getAccounts: jest.fn(),
  getChainId: jest.fn(),
  isConnected: false,
  isConnecting: false,
  isDisconnected: true,
  isUnsupported: false,
  switchChain: jest.fn(),
  watchAccount: jest.fn(),
  watchChainId: jest.fn(),
  watchConnector: jest.fn(),
  watchDisconnect: jest.fn(),
})
