/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface CellarRouterV0815Interface extends utils.Interface {
  functions: {
    "depositAndSwapIntoCellar(address,address[],uint24[],uint256,uint256,address)": FunctionFragment;
    "depositAndSwapIntoCellarWithPermit(address,address[],uint24[],uint256,uint256,address,uint256,bytes)": FunctionFragment;
    "depositIntoCellarWithPermit(address,uint256,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "uniswapV2Router()": FunctionFragment;
    "uniswapV3Router()": FunctionFragment;
    "withdrawAndSwapFromCellar(address,address[],uint24[],uint256,uint256,address)": FunctionFragment;
    "withdrawAndSwapFromCellarWithPermit(address,address[],uint24[],uint256,uint256,address,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "depositAndSwapIntoCellar"
      | "depositAndSwapIntoCellarWithPermit"
      | "depositIntoCellarWithPermit"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "uniswapV2Router"
      | "uniswapV3Router"
      | "withdrawAndSwapFromCellar"
      | "withdrawAndSwapFromCellarWithPermit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositAndSwapIntoCellar",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndSwapIntoCellarWithPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositIntoCellarWithPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV2Router",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3Router",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAndSwapFromCellar",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAndSwapFromCellarWithPermit",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositAndSwapIntoCellar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndSwapIntoCellarWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositIntoCellarWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV2Router",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3Router",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAndSwapFromCellar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAndSwapFromCellarWithPermit",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface CellarRouterV0815 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CellarRouterV0815Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositAndSwapIntoCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositAndSwapIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      assets: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uniswapV2Router(overrides?: CallOverrides): Promise<[string]>;

    uniswapV3Router(overrides?: CallOverrides): Promise<[string]>;

    withdrawAndSwapFromCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawAndSwapFromCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  depositAndSwapIntoCellar(
    cellar: PromiseOrValue<string>,
    path: PromiseOrValue<string>[],
    poolFees: PromiseOrValue<BigNumberish>[],
    assets: PromiseOrValue<BigNumberish>,
    assetsOutMin: PromiseOrValue<BigNumberish>,
    receiver: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositAndSwapIntoCellarWithPermit(
    cellar: PromiseOrValue<string>,
    path: PromiseOrValue<string>[],
    poolFees: PromiseOrValue<BigNumberish>[],
    assets: PromiseOrValue<BigNumberish>,
    assetsOutMin: PromiseOrValue<BigNumberish>,
    receiver: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositIntoCellarWithPermit(
    cellar: PromiseOrValue<string>,
    assets: PromiseOrValue<BigNumberish>,
    receiver: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uniswapV2Router(overrides?: CallOverrides): Promise<string>;

  uniswapV3Router(overrides?: CallOverrides): Promise<string>;

  withdrawAndSwapFromCellar(
    cellar: PromiseOrValue<string>,
    path: PromiseOrValue<string>[],
    poolFees: PromiseOrValue<BigNumberish>[],
    assets: PromiseOrValue<BigNumberish>,
    assetsOutMin: PromiseOrValue<BigNumberish>,
    receiver: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawAndSwapFromCellarWithPermit(
    cellar: PromiseOrValue<string>,
    path: PromiseOrValue<string>[],
    poolFees: PromiseOrValue<BigNumberish>[],
    assets: PromiseOrValue<BigNumberish>,
    assetsOutMin: PromiseOrValue<BigNumberish>,
    receiver: PromiseOrValue<string>,
    deadline: PromiseOrValue<BigNumberish>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositAndSwapIntoCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositAndSwapIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      assets: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapV2Router(overrides?: CallOverrides): Promise<string>;

    uniswapV3Router(overrides?: CallOverrides): Promise<string>;

    withdrawAndSwapFromCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawAndSwapFromCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    depositAndSwapIntoCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositAndSwapIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      assets: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    uniswapV2Router(overrides?: CallOverrides): Promise<BigNumber>;

    uniswapV3Router(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawAndSwapFromCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawAndSwapFromCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositAndSwapIntoCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositAndSwapIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositIntoCellarWithPermit(
      cellar: PromiseOrValue<string>,
      assets: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uniswapV2Router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uniswapV3Router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawAndSwapFromCellar(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAndSwapFromCellarWithPermit(
      cellar: PromiseOrValue<string>,
      path: PromiseOrValue<string>[],
      poolFees: PromiseOrValue<BigNumberish>[],
      assets: PromiseOrValue<BigNumberish>,
      assetsOutMin: PromiseOrValue<BigNumberish>,
      receiver: PromiseOrValue<string>,
      deadline: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
