name: Alpha stETH Deposits Report

on:
  schedule:
    - cron: "15 5 * * *" # daily 05:15 UTC
  workflow_dispatch:

concurrency:
  group: tg-alpha-steth
  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps (no scripts)
        run: |
          corepack enable
          pnpm -v || npm i -g pnpm@9
          pnpm install --frozen-lockfile=false --ignore-scripts

      - name: Validate production data
        env:
          REPORT_API_BASE: ${{ secrets.REPORT_API_BASE }}
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
          NEXT_PUBLIC_ATTRIBUTION_ENABLED: "true"
          START_BLOCK_ALPHA_STETH: ${{ secrets.START_BLOCK_ALPHA_STETH }}
          ALLOWED_API_HOSTS: ".somm.finance,.sommelier.finance"
        run: |
          echo "Validating production data source..."
          node scripts/analytics/generate-alpha-deposits.mjs --validate-only
          echo "✅ Alpha stETH validation passed against $REPORT_API_BASE" >> $GITHUB_STEP_SUMMARY

      - name: Upload validation failure report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: validation-failure-report
          path: docs/analytics/validation-fail.md
          retention-days: 30

      - name: Generate deposits report (no Telegram)
        if: success()
        env:
          REPORT_API_BASE: ${{ secrets.REPORT_API_BASE }}
          START_BLOCK_ALPHA_STETH: ${{ secrets.START_BLOCK_ALPHA_STETH }}
          # TELEGRAM_MODE not set - will disable Telegram posting
        run: |
          echo "Validation passed. Generating report (Telegram disabled)..."
          node scripts/analytics/generate-alpha-deposits.mjs

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore(analytics): update Alpha stETH deposits report"

      - name: Push
        if: ${{ success() }}
        run: |
          git push
