name: Tests

on:
  pull_request:
    # Run for PRs into any branch (safe: no secrets used)
    branches: ['**']
  push:
    # Run on pushes to any branch to validate before PR is opened
    branches: ['**']

jobs:
  unit_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm run typecheck:scoped
      - name: Lint (scoped)
        run: pnpm run lint:scoped
      - name: Test with coverage
        run: pnpm run test:all -- --coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-jest
          path: coverage

  e2e:
    runs-on: ubuntu-latest
    needs: unit_integration
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report


