name: Tests

on:
  pull_request:
    # Run for PRs into any branch (safe: no secrets used)
    branches: ['**']
  push:
    # Run on pushes to any branch to validate before PR is opened
    branches: ['**']

jobs:
  unit_integration:
    runs-on: ubuntu-latest
    env:
      KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
      KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
      NEXT_PUBLIC_ATTRIBUTION_ENABLED: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Print versions
        run: |
          echo "Node.js version:"
          node -v
          echo "pnpm version:"
          pnpm -v
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Checking if node_modules exists:"
          ls -la node_modules || echo "node_modules does not exist yet"
      - name: Check package.json
        run: |
          echo "Package.json contents:"
          cat package.json | grep -A 10 -B 5 "eslint"
      - name: Setup pnpm store cache
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install deps (with retry)
        run: |
          for i in 1 2 3; do
            echo "Installation attempt $i..."
            pnpm install --frozen-lockfile && echo "Installation successful" && break || echo "pnpm install failed (attempt $i), retrying in 10s" && sleep 10;
          done
      - name: Verify installation
        run: |
          echo "Verifying installation..."
          echo "node_modules exists:"
          ls -la node_modules || echo "node_modules not found"
          echo "ESLint binary exists:"
          ls -la node_modules/.bin/eslint || echo "ESLint binary not found"
          echo "pnpm list output:"
          pnpm list --depth=0 | grep eslint || echo "ESLint not found in pnpm list"
      - name: Verify ESLint installation
        run: |
          echo "Checking if ESLint is installed..."
          pnpm list eslint
          echo "ESLint version:"
          pnpm exec eslint --version
      - name: Create reports directory
        run: mkdir -p reports
      - name: Typecheck
        run: pnpm run typecheck:scoped
      - name: Lint (repo, strict)
        run: pnpm run lint:ci
      - name: Upload ESLint JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-junit
          path: reports/eslint-junit.xml
      - name: Test with coverage
        run: pnpm run test:all -- --coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-jest
          path: coverage

  e2e:
    runs-on: ubuntu-latest
    needs: unit_integration
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Setup pnpm store cache
        id: pnpm-cache-e2e
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache-e2e.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install deps (with retry)
        run: |
          for i in 1 2 3; do
            pnpm install --frozen-lockfile --network-timeout 300000 && break || echo "pnpm install failed (attempt $i), retrying in 10s" && sleep 10;
          done
      - name: Verify dependencies
        run: |
          echo "Checking if dependencies are installed..."
          pnpm list --depth=0
      - name: Build
        run: pnpm build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report


